name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '12.x'
      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'beta'
      - name: Get dependencies
        run: flutter pub get
      - name: Format source code
        run: flutter format lib/** --set-exit-if-changed .
      - name: Analyze source code
        run: flutter analyze .
      - name: Build Android application
        run: flutter build apk
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk-${{ github.ref }}
          path: build/app/outputs/apk/release/app-release.apk
  release:
    name: Release application to GitHub Releases
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: release-apk
      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Flutter WorldTime ${{ github.ref }}
      - name: Upload asset to GitHub
        uses: shogo82148/actions-upload-release-asset@v1.6.0
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: build/app/outputs/apk/release/app-release.apk