name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Get dependencies
        run: flutter pub get
      - name: Format source code
        run: flutter format lib/** --set-exit-if-changed .
      - name: Analyze source code
        run: flutter analyze .
      - name: Build Android application
        run: flutter build apk
      - name: Upload Android application
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
  release:
    name: Release application to GitHub Releases
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: release-apk
      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Flutter WorldTime V${{ github.run_number }}
      - name: Upload asset to GitHub
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: build/app/outputs/apk/release/app-release.apk
          asset_name: flutter-worldtime-v${{ github.run_number }}.apk
          asset_content_type: application/zip