name: Flutter CI Release

on: 
  push:
    tags:
      - '*'

jobs:
  releases:
    name: Release .apk
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "12.x"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: $
      - uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: $
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk --release
      - uses: ncipollo/release-action@v1
        with:
         artifacts: "build/app/outputs/flutter-apk/*.apk"
         token: $